### ISSUE TITLE
Correct wiring

### ISSUE THREAD

**Issue by ChalidNL** [zuidwijk/esphome-doorbell-with-mute#1]
Hi,

Thanks for sharing your project. I have tried to wire it but I was unable to get the same result as described. 

Currently my doorbell has two wires that go into the WEMOS d2 and the 3v3. The bell does ring and the status of the binary sensor says its on. But I believe the basic state should be off and whenver its pressed it should switch from off to on?

Whenever its is pressed it will change state from on to off and off to on.

Can you advice me how to wire.

Thanks!

BR Chalid

**Comment by zuidwijk** [comment]
Did you also use a resistor between the 3v3 and D2? 

See for more info my website: https://www.zuidwijk.com/domotica/making-my-doorbell-smart/

**Comment by ChalidNL** [comment]
> Did you also use a resistor between the 3v3 and D2?
> 
> See for more info my website: https://www.zuidwijk.com/domotica/making-my-doorbell-smart/

No I did not do that. So there needs to be a resistor between 3v3 and d2. Where should the button wires go to?

**Comment by zuidwijk** [comment]
No wait, not the 3v3... then the D2 will always be high (sorry, my mistake). 
The resistor needs to between GND and D2, so that D2 will be low when button is not pressed. And once the button is pressed, it will be hight.

Please read it on my website: https://www.zuidwijk.com/domotica/making-my-doorbell-smart/

> For the trigger I used the 3.3v on the D2. D2 is shorted to the ground via a resistor, and is high when pressed on the doorbell. This resister is needed to make sure that the input is only high when doorbell is pressed and is low on release.

So the button is connected to the 3v3 and D2, so it will trigger the D2 to high, and on release it will be low again because of the resistor.
